#@ load("@ytt:data", "data")
---
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tap-development
spec:
  title: Experimental
  description: Pre-release development version of the TAP Demo
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: https://github.com/tanzu-end-to-end/tap-workshop
  content:
    image: #@ "harbor.{}/tanzu-e2e/eduk8s-tap-workshop:latest".format(data.values.ingress.domain)
    files: #@ "github.com/{}/tap-workshop?ref={}".format(data.values.git.account,data.values.git.branch)
  session:
    env:
      - name: GITEA_PASSWORD
        value: #@ data.values.gitea.adminPassword
      - name: HARBOR_PASSWORD
        value: #@ data.values.harbor.adminPassword
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
    objects:
      - apiVersion: v1
        kind: LimitRange
        metadata:
          name: resource-limits
        spec:
          limits:
            - type: PersistentVolumeClaim
              max:
                storage: 10Gi

      - apiVersion: e2e.tanzu.vmware.com/v1beta1
        kind: HarborProject
        metadata:
          name: $(session_namespace)
          annotations:
            training.eduk8s.io/objects.crd.scope: Namespaced
        spec:
          name: $(session_namespace)

      - apiVersion: v1
        kind: Secret
        metadata:
          name: tap-registry
          annotations:
            secretgen.carvel.dev/image-pull-secret: ""
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: e30K

      - apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: tap-sa
        secrets:
          - name: registry-credentials
        imagePullSecrets:
          - name: registry-credentials
          - name: tap-registry

      - apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          name: service-account-role
          namespace: $(session_namespace)
        rules:
          - apiGroups: ["*"]
            resources: ["*"]
            verbs: ["*"]

      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: $(session_namespace)-binding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: service-account-role
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: $(service_account)

      - apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: $(session_namespace)-supply-chain-binding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: Role
          name: service-account-role
        subjects:
          - kind: ServiceAccount
            namespace: $(workshop_namespace)
            name: tap-sa

#      - apiVersion: rbac.authorization.k8s.io/v1
#        kind: ClusterRole
#        metadata:
#          name: service-binding-rmq
#          labels:
#            servicebinding.io/controller: "true"
#        rules:
#          - apiGroups: ["rabbitmq.com"]
#            resources: ["rabbitmqclusters"]
#            verbs: ["get", "list", "watch"]

#      - apiVersion: v1
#        kind: ServiceAccount
#        metadata:
#          name: app-live-view-connector-service-account
#          namespace: $(session_namespace)
#      - apiVersion: rbac.authorization.k8s.io/v1
#        kind: ClusterRole
#        metadata:
#          name: $(session_namespace)-app-live-view-connector-service-account-cluster-role
#        rules:
#          - apiGroups: ["*"]
#            resources: ["pods"]
#            verbs: ["watch"]
#      - apiVersion: rbac.authorization.k8s.io/v1
#        kind: RoleBinding
#        metadata:
#          name: $(session_namespace)-app-live-view-connector-role-binding
#        roleRef:
#          apiGroup: rbac.authorization.k8s.io
#          kind: ClusterRole
#          name: $(session_namespace)-app-live-view-connector-service-account-cluster-role
#        subjects:
#          - kind: ServiceAccount
#            name: app-live-view-connector-service-account
#            namespace: $(session_namespace)
