apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tap-demos
spec:
  portal:
    title: Tanzu Application Platform Demos
    password: tanzu
    ingress:
      hostname: tap-demos
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 5
  workshops:
    - name: tap-overview
      expires: 240m
      orphaned: 45m
      capacity: 5
      reserved: 0
      initial: 0
      env:
      - name: DATASTORE_USERNAME
        value: admin
      - name: DATASTORE_PASSWORD
        value: admin123!
    - name: tap-devx-deepdive
      expires: 240m
      orphaned: 45m
      capacity: 5
      reserved: 0
      initial: 0
      env:
      - name: DATASTORE_USERNAME
        value: admin
      - name: DATASTORE_PASSWORD
        value: admin123!
    - name: tap-operator-deepdive
      expires: 240m
      orphaned: 45m
      capacity: 5
      reserved: 0
      initial: 0
      env:
      - name: DATASTORE_USERNAME
        value: admin
      - name: DATASTORE_PASSWORD
        value: admin123!
