apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tap-demos
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Platform Demos
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 10
  workshops:
#    - name: tap-overview
#      expires: 60m
#      orphaned: 20m
#      capacity: 20
#      reserved: 0
    - name: tap-development
      expires: 60m
      orphaned: 20m
      capacity: 10
      reserved: 0
