apiVersion: training.eduk8s.io/v1alpha1
kind: TrainingPortal
metadata:
  name: tap-demos
  annotations:
    kapp.k14s.io/update-strategy: always-replace
spec:
  portal:
    title: Tanzu Application Platform Demos
    password: tanzu
    registration:
      type: one-step
      enabled: false
    updates:
      workshop: true
    sessions:
      maximum: 5
  workshops:
    - name: tap-overview
      expires: 240m
      orphaned: 45m
      capacity: 5
      reserved: 2
      initial: 0
      env:
      - name: DATASTORE_USERNAME
        value: admin
      - name: DATASTORE_PASSWORD
        value: admin123!
